<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <AssemblyName>MinecraftControlCenter</AssemblyName>
    <RootNamespace>MinecraftControlCenter</RootNamespace>
    <ApplicationIcon>assets\MinecraftControlCenter.ico</ApplicationIcon>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <LangVersion>latest</LangVersion>
    <SupportedOSPlatformVersion>6.1</SupportedOSPlatformVersion>
    <NoWarn>$(NoWarn);CA1416;SYSLIB0014</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Management" Version="8.0.0" />
    <EmbeddedResource Include="assets\minecraftbackground.jpg" LogicalName="MinecraftControlCenter.Background.jpg" />
    <EmbeddedResource Include="assets\MinecraftControlCenter.ico" LogicalName="MinecraftControlCenter.Icon.ico" />
  </ItemGroup>
</Project>
